image: debian/buster
packages:
- curl
- gpg
- apt-transport-https
secrets:
  - 7bb48981-fc03-4344-bae3-736c99f94f49 # docker_user
  - 21bdadaa-095c-4968-9a6e-ce9b795042b4 # docker_pass
sources:
  - https://github.com/alexeldeib/az-local-pvc
environment:
  APP: az-local-pvc
  REPO: docker.io/alexeldeib
tasks:
- install: |
    bash ~/az-local-pvc/hack/setup_docker.sh
- build: |
    bash ~/az-local-pvc/hack/build.sh
