name: az-local-pvc

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  REPO: docker.io/alexeldeib
  IMAGE: az-local-pvc

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build image
      run: |
        set -eux
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        TAG=$(date -Iseconds | tr :+ -)
        echo "TAG: ${TAG}"
        docker build -t ${REPO}/${IMAGE}:${TAG} .
        docker tag ${REPO}/${IMAGE}:${TAG} ${REPO}/${IMAGE}:latest
        docker push ${REPO}/${IMAGE}:${TAG}
        docker push ${REPO}/${IMAGE}:latest
